version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd site
      - npm install
      - npm i -g serverless
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=$aws_access_key_id
      - export AWS_SECRET_ACCESS_KEY=$aws_secret_access_key
      - serverless deploy

