version: '3'
services:
  site:
    build: ./site
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network
  api:
    build: ./api
    ports:
      - "3001:3001"
   
    networks:
      - app-network

networks:
  app-network: