name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Reemplaza con la versión de Node.js que uses

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Run unit tests
      run: npm test